In [ ]:
#Simulando erro obs: se tiver encoding utf-8 padrao o pandas ler sem precisar passar parametro encoding
import pandas as pd

#pd.set_option('display.max_columns', None)# ver todas as colunas  
caminho_do_arquivo = r"F:\GitHub\python-multi-database-integration\Data\V_OCORRENCIA_AMPLA.json"
df = pd.read_json(caminho_do_arquivo) 
df.head()

codecs / encoding

https://docs.python.org/pt-br/3/library/codecs.html

O BOM (Byte Order Mark) é uma sequência de bytes especial no início de um arquivo de texto para indicar a codificação do texto e a ordem dos bytes. será lido como binario e nao como texto

In [9]:
import pandas as pd
caminho_do_arquivo = r"F:\GitHub\python-multi-database-integration\Data\V_OCORRENCIA_AMPLA.json"
df = pd.read_json(caminho_do_arquivo, encoding='utf-8-sig')
df.head()

,Numero_da_Ocorrencia,Numero_da_Ficha,Operador_Padronizado,Classificacao_da_Ocorrência,Data_da_Ocorrencia,Hora_da_Ocorrência,Municipio,UF,Regiao,Descricao_do_Tipo,...,Lesoes_Desconhecidas_Tripulantes,Lesoes_Desconhecidas_Passageiros,Lesoes_Desconhecidas_Terceiros,Modelo,CLS,Tipo_ICAO,PMD,Numero_de_Assentos,Nome_do_Fabricante,PSSO
0,7762,201803231711488,ICON TAXI AEREO LTDA E OUTRO,Incidente,2018-03-21,20:00:00,SÃO PAULO,SP,Sudeste,FALHA OU MAU FUNCIONAMENTO DE SISTEMA / COMPON...,...,0.0,0.0,0.0,AW109SP,H2T,A109,3175.0,8.0,AGUSTA,verdadeiro
1,7759,201803161337187,EJ ESCOLA DE AERONAUTICA CIVIL LTDA,Acidente,2018-03-14,15:30:00,MONTES CLAROS,MG,Sudeste,COMBUSTÍVEL,...,0.0,0.0,0.0,A152,L1P,C152,757.0,2.0,CESSNA AIRCRAFT,verdadeiro
2,7758,201802271904132,AEROTEX AVIACAO AGRICOLA LTDA.,Acidente,2018-01-26,12:20:00,INACIOLÂNDIA,GO,Centro-Oeste,EXCURSÃO DE PISTA,...,0.0,0.0,0.0,T188C,L1P,C188,1997.0,1.0,CESSNA AIRCRAFT,verdadeiro
3,7758,201802271904132,AEROTEX AVIACAO AGRICOLA LTDA.,Acidente,2018-01-26,12:20:00,INACIOLÂNDIA,GO,Centro-Oeste,INCURSÃO EM PISTA,...,0.0,0.0,0.0,T188C,L1P,C188,1997.0,1.0,CESSNA AIRCRAFT,verdadeiro
4,7757,201803191230508,REALIZAR ESCOLA DE AVIACAO CIVIL LTDA,Incidente Grave,2018-03-18,20:30:00,TORRES,RS,Sul,CONTATO ANORMAL COM A PISTA,...,0.0,0.0,0.0,PA-34-200,L2P,PA34,1814.0,6.0,PIPER AIRCRAFT,verdadeiro

https://chardet.readthedocs.io/en/latest/usage.html

In [10]:
#pip install chardet
import codecs
from chardet import UniversalDetector

caminho_do_arquivo = r"F:\GitHub\python-multi-database-integration\Data\V_OCORRENCIA_AMPLA.json"
detector = UniversalDetector()

with open(caminho_do_arquivo, 'rb') as arquivo: #rb esta lendo como binario em forma de bits no lugar de texto ou outra coisa 
    for linha in arquivo:
        detector.feed(linha)
        if detector.done:
            break

detector.close()
encoding_detectado = detector.result['encoding']

print(encoding_detectado)


'''
from chardet import UniversalDetector

detector = UniversalDetector()
with open("somefile.txt", "rb") as f:
    for line in f:
        detector.feed(line)
        if detector.done:
            break
detector.close()
print(detector.result)
'''

UTF-8-SIG

'\nfrom chardet import UniversalDetector\n\ndetector = UniversalDetector()\nwith open("somefile.txt", "rb") as f:\n    for line in f:\n        detector.feed(line)\n        if detector.done:\n            break\ndetector.close()\nprint(detector.result)\n'

https://docs.python.org/pt-br/3/library/json.html

https://docs.python.org/3/library/stdtypes.html#str

In [14]:
import json
import codecs

#pd.set_option('display.max_columns', None)# ver todas as colunas  voce pode usar para Df com muitas colunas e quer ver todas
caminho_do_arquivo = r"F:\GitHub\python-multi-database-integration\Data\V_OCORRENCIA_AMPLA.json"

with codecs.open(caminho_do_arquivo, 'r', encoding='utf-8-sig') as arquivo:
    data = json.load(arquivo)
df_json = pd.json_normalize(data)
df_json.head()

C:\Users\luana_qf6csq7\AppData\Local\Temp\ipykernel_11348\222233165.py:7: DeprecationWarning: codecs.open() is deprecated. Use open() instead.
  with codecs.open(caminho_do_arquivo, 'r', encoding='utf-8-sig') as arquivo:

,Numero_da_Ocorrencia,Numero_da_Ficha,Operador_Padronizado,Classificacao_da_Ocorrência,Data_da_Ocorrencia,Hora_da_Ocorrência,Municipio,UF,Regiao,Descricao_do_Tipo,ICAO,Latitude,Longitude,Tipo_de_Aerodromo,Historico,Matricula,Categoria_da_Aeronave,Operador,Tipo_de_Ocorrencia,Fase_da_Operacao,Operacao,Danos_a_Aeronave,Aerodromo_de_Destino,Aerodromo_de_Origem,Lesoes_Fatais_Tripulantes,Lesoes_Fatais_Passageiros,Lesoes_Fatais_Terceiros,Lesoes_Graves_Tripulantes,Lesoes_Graves_Passageiros,Lesoes_Graves_Terceiros,Lesoes_Leves_Tripulantes,Lesoes_Leves_Passageiros,Lesoes_Leves_Terceiros,Ilesos_Tripulantes,Ilesos_Passageiros,Lesoes_Desconhecidas_Tripulantes,Lesoes_Desconhecidas_Passageiros,Lesoes_Desconhecidas_Terceiros,Modelo,CLS,Tipo_ICAO,PMD,Numero_de_Assentos,Nome_do_Fabricante,PSSO
0,7762,201803231711488,ICON TAXI AEREO LTDA E OUTRO,Incidente,2018-03-21,20:00:00,SÃO PAULO,SP,Sudeste,FALHA OU MAU FUNCIONAMENTO DE SISTEMA / COMPON...,NaN,"-23,6261","-46,6564",NaN,DURANTE O VOO O PILOTO SENTIU A AERONAVE COM P...,PRROS,TPX,ICON TAXI AEREO LTDA E OUTRO,SCF-NP,Pouso,Táxi Aéreo,Nenhum,SBSP,SDSC,0,0,0,0,0,0,0,0,0,2,0,0,0,0,AW109SP,H2T,A109,3175,8,AGUSTA,verdadeiro
1,7759,201803161337187,EJ ESCOLA DE AERONAUTICA CIVIL LTDA,Acidente,2018-03-14,15:30:00,MONTES CLAROS,MG,Sudeste,COMBUSTÍVEL,Fora de Aeródromo,"-16,7861","-43,8817",-,QUANDO A AERONAVE ATINGIU 6 MILHAS AO SUL DO A...,PREJO,PRI,EJ ESCOLA DE AERONAUTICA LTDA,FUEL,Em rota,Voo de Instrução,Substancial,SBMK,SIMK,0,0,0,0,0,0,0,0,0,1,1,0,0,0,A152,L1P,C152,757,2,CESSNA AIRCRAFT,verdadeiro
2,7758,201802271904132,AEROTEX AVIACAO AGRICOLA LTDA.,Acidente,2018-01-26,12:20:00,INACIOLÂNDIA,GO,Centro-Oeste,EXCURSÃO DE PISTA,NaN,"-18,4572","-49,9842",NaN,A AERONAVE DECOLAVA DE UMA PISTA DE POUSO EVEN...,PTWZP,S11,AEROTEX AVIAÇÃO AGRÍCOLA LTDA.,RE,Decolagem,Operação Agrícola,Substancial,NaN,NaN,0,0,0,0,0,0,0,0,0,1,0,0,0,0,T188C,L1P,C188,1997,1,CESSNA AIRCRAFT,verdadeiro
3,7758,201802271904132,AEROTEX AVIACAO AGRICOLA LTDA.,Acidente,2018-01-26,12:20:00,INACIOLÂNDIA,GO,Centro-Oeste,INCURSÃO EM PISTA,NaN,"-18,4572","-49,9842",NaN,A AERONAVE DECOLAVA DE UMA PISTA DE POUSO EVEN...,PTWZP,S11,AEROTEX AVIAÇÃO AGRÍCOLA LTDA.,RI,Decolagem,Operação Agrícola,Substancial,NaN,NaN,0,0,0,0,0,0,0,0,0,1,0,0,0,0,T188C,L1P,C188,1997,1,CESSNA AIRCRAFT,verdadeiro
4,7757,201803191230508,REALIZAR ESCOLA DE AVIACAO CIVIL LTDA,Incidente Grave,2018-03-18,20:30:00,TORRES,RS,Sul,CONTATO ANORMAL COM A PISTA,NaN,"-29,4153","-49,8106",NaN,"A AERONAVE DECOLOU DE TORRES (SBTR), RS , ÀS 1...",PRRLY,PRI,REALIZAR ESCOLA DE AVIAÇÃO CIVIL LTDA,ARC,Pouso,Voo de Instrução,Leve,SBTR,SBTR,0,0,0,0,0,0,0,0,0,2,0,0,0,0,PA-34-200,L2P,PA34,1814,6,PIPER AIRCRAFT,verdadeiro

Carregando automaticamente encoding

In [19]:
import pandas as pd
from chardet import UniversalDetector

#pd.set_option('display.max_columns', None)
caminho_do_arquivo = r"F:\GitHub\python-multi-database-integration\Data\V_OCORRENCIA_AMPLA.json"
detector = UniversalDetector()

with open(caminho_do_arquivo, 'rb') as arquivo: #rb esta lendo como binario em forma de bits no lugar de texto ou outra coisa 
    for linha in arquivo:
        detector.feed(linha)
        if detector.done:
            break
detector.close()
encoding_detectado = detector.result['encoding']

df_json_automatico = pd.read_json(caminho_do_arquivo, encoding=encoding_detectado)
df_json_automatico.head()

,Numero_da_Ocorrencia,Numero_da_Ficha,Operador_Padronizado,Classificacao_da_Ocorrência,Data_da_Ocorrencia,Hora_da_Ocorrência,Municipio,UF,Regiao,Descricao_do_Tipo,ICAO,Latitude,Longitude,Tipo_de_Aerodromo,Historico,Matricula,Categoria_da_Aeronave,Operador,Tipo_de_Ocorrencia,Fase_da_Operacao,Operacao,Danos_a_Aeronave,Aerodromo_de_Destino,Aerodromo_de_Origem,Lesoes_Fatais_Tripulantes,Lesoes_Fatais_Passageiros,Lesoes_Fatais_Terceiros,Lesoes_Graves_Tripulantes,Lesoes_Graves_Passageiros,Lesoes_Graves_Terceiros,Lesoes_Leves_Tripulantes,Lesoes_Leves_Passageiros,Lesoes_Leves_Terceiros,Ilesos_Tripulantes,Ilesos_Passageiros,Lesoes_Desconhecidas_Tripulantes,Lesoes_Desconhecidas_Passageiros,Lesoes_Desconhecidas_Terceiros,Modelo,CLS,Tipo_ICAO,PMD,Numero_de_Assentos,Nome_do_Fabricante,PSSO
0,7762,201803231711488,ICON TAXI AEREO LTDA E OUTRO,Incidente,2018-03-21,20:00:00,SÃO PAULO,SP,Sudeste,FALHA OU MAU FUNCIONAMENTO DE SISTEMA / COMPON...,NaN,"-23,6261","-46,6564",NaN,DURANTE O VOO O PILOTO SENTIU A AERONAVE COM P...,PRROS,TPX,ICON TAXI AEREO LTDA E OUTRO,SCF-NP,Pouso,Táxi Aéreo,Nenhum,SBSP,SDSC,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,AW109SP,H2T,A109,3175.0,8.0,AGUSTA,verdadeiro
1,7759,201803161337187,EJ ESCOLA DE AERONAUTICA CIVIL LTDA,Acidente,2018-03-14,15:30:00,MONTES CLAROS,MG,Sudeste,COMBUSTÍVEL,Fora de Aeródromo,"-16,7861","-43,8817",-,QUANDO A AERONAVE ATINGIU 6 MILHAS AO SUL DO A...,PREJO,PRI,EJ ESCOLA DE AERONAUTICA LTDA,FUEL,Em rota,Voo de Instrução,Substancial,SBMK,SIMK,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,A152,L1P,C152,757.0,2.0,CESSNA AIRCRAFT,verdadeiro
2,7758,201802271904132,AEROTEX AVIACAO AGRICOLA LTDA.,Acidente,2018-01-26,12:20:00,INACIOLÂNDIA,GO,Centro-Oeste,EXCURSÃO DE PISTA,NaN,"-18,4572","-49,9842",NaN,A AERONAVE DECOLAVA DE UMA PISTA DE POUSO EVEN...,PTWZP,S11,AEROTEX AVIAÇÃO AGRÍCOLA LTDA.,RE,Decolagem,Operação Agrícola,Substancial,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,T188C,L1P,C188,1997.0,1.0,CESSNA AIRCRAFT,verdadeiro
3,7758,201802271904132,AEROTEX AVIACAO AGRICOLA LTDA.,Acidente,2018-01-26,12:20:00,INACIOLÂNDIA,GO,Centro-Oeste,INCURSÃO EM PISTA,NaN,"-18,4572","-49,9842",NaN,A AERONAVE DECOLAVA DE UMA PISTA DE POUSO EVEN...,PTWZP,S11,AEROTEX AVIAÇÃO AGRÍCOLA LTDA.,RI,Decolagem,Operação Agrícola,Substancial,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,T188C,L1P,C188,1997.0,1.0,CESSNA AIRCRAFT,verdadeiro
4,7757,201803191230508,REALIZAR ESCOLA DE AVIACAO CIVIL LTDA,Incidente Grave,2018-03-18,20:30:00,TORRES,RS,Sul,CONTATO ANORMAL COM A PISTA,NaN,"-29,4153","-49,8106",NaN,"A AERONAVE DECOLOU DE TORRES (SBTR), RS , ÀS 1...",PRRLY,PRI,REALIZAR ESCOLA DE AVIAÇÃO CIVIL LTDA,ARC,Pouso,Voo de Instrução,Leve,SBTR,SBTR,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,PA-34-200,L2P,PA34,1814.0,6.0,PIPER AIRCRAFT,verdadeiro